// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PearlMetric.GatewayApi.Data;

#nullable disable

namespace GatewayApi.Migrations
{
    [DbContext(typeof(PearlMetricDb))]
    partial class PearlMetricDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.CalibrationProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AlignmentMatrixJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CalibratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("CalibrationReferenceValue")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ScanRunId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ScanRunId")
                        .IsUnique();

                    b.ToTable("CalibrationProfiles");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.ColorMetricSample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("A")
                        .HasColumnType("double precision");

                    b.Property<double>("B")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("double precision");

                    b.Property<double>("DeltaE")
                        .HasColumnType("double precision");

                    b.Property<double>("L")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ScanRunId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceIndex")
                        .HasColumnType("integer");

                    b.Property<string>("ShadeGuideValue")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScanRunId", "SequenceIndex");

                    b.ToTable("ColorMetricSamples");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.ScanRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RegimenId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegimenId");

                    b.ToTable("Runs");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.WhiteningRegimen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ScheduledIntervalHours")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Regimens");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.CalibrationProfile", b =>
                {
                    b.HasOne("PearlMetric.GatewayApi.Models.ScanRun", "ScanRun")
                        .WithOne("Calibration")
                        .HasForeignKey("PearlMetric.GatewayApi.Models.CalibrationProfile", "ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.ColorMetricSample", b =>
                {
                    b.HasOne("PearlMetric.GatewayApi.Models.ScanRun", "ScanRun")
                        .WithMany("Samples")
                        .HasForeignKey("ScanRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScanRun");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.ScanRun", b =>
                {
                    b.HasOne("PearlMetric.GatewayApi.Models.WhiteningRegimen", "Regimen")
                        .WithMany("Runs")
                        .HasForeignKey("RegimenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regimen");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.WhiteningRegimen", b =>
                {
                    b.HasOne("PearlMetric.GatewayApi.Models.Patient", "Patient")
                        .WithMany("Regimens")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.Patient", b =>
                {
                    b.Navigation("Regimens");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.ScanRun", b =>
                {
                    b.Navigation("Calibration");

                    b.Navigation("Samples");
                });

            modelBuilder.Entity("PearlMetric.GatewayApi.Models.WhiteningRegimen", b =>
                {
                    b.Navigation("Runs");
                });
#pragma warning restore 612, 618
        }
    }
}
